import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroWrapper from "@/components/HeroWrapper"; // Import the new wrapper

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Watch Live TV, Sports, News, and Movies Free Online - Plex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hostGrotesk.variable} antialiased`}>
        <Navbar />
        <HeroWrapper />{" "}
        {/* HeroWrapper will conditionally render HeroSection */}
        {children}
      </body>
    </html>
  );
}
